#!/usr/bin/env bash
# 04-hai-up.sh —— 生成 config.sh 并执行 `hai-up up`，随后做本环境必需的加固。
#
# 与 VM 集群那套（terraform-hai-platform）的差异：
#   * KUBECONFIG 指向单节点集群 /root/.kube/hai-single.conf（写进 config.sh，hai-up 会把它
#     复制进 ${HAI_PLATFORM_PATH}/kubeconfig/ 供平台 Pod 内的 launcher/manager 使用）；
#   * SHARED_FS_ROOT=/nfs-shared/hai-single —— 与 VM 平台的 /nfs-shared/hai-platform **完全隔离**；
#   * 单节点：TRAINING_NODES = MANAGER_NODES = 本节点；JUPYTER_NODES 必须"非空但不含任何节点"，
#     因为 one/hai-up.sh 用 `: ${JUPYTER_NODES:=<假节点>}`（空值会被替换成 cn-hangzhou.172.23.183.226，
#     于是 DB 里会多出一个不存在的 jupyter 节点；写成空格则数组为空、不产生任何 jupyter host 行）；
#   * NODE_GPUS=1（本机就一块 V100；老环境默认 4 会把卡分错）；
#   * HAI_SERVER_ADDR / INGRESS_HOST 直接用 MetalLB 的 LAN VIP（Mac 可直达，无需 nginx 反代）。
#
# 本机没有内网 registry，平台镜像只是 docker save → ctr -n k8s.io import 进来的，
# 因此必须在 hai-up 之后做三处修补（E/F/G）——见各步骤注释。

set -euo pipefail
source "$(dirname "$0")/lib.sh"

step "A. 写 config.sh（${CONFIG_PATH}）"
sudo mkdir -p "$HAI_DIR"
TMP_CFG="$(mktemp)"
# BFF_ADMIN_TOKEN 必须**跨 run 稳定**：init.sql 只在**首次** init 时写入 bff_admin 这一行，
# 而本模块默认保留 ${HAI_DIR}/db（不像 VM 模块每次清库）。若每次 run 都换随机 token，
# DB 里的 bff_admin.token 就会与容器 env 不一致 → studio 的内部调用
# （/query/user/training_quota/list_all、/query/user/info 等）全部 403
# → 前端 data_panel 接口 500（实测：UI 卡在 Fetching User Info）。
BFF_TOKEN_FILE="${HAI_DIR}/.bff_admin_token"
if ! sudo test -s "$BFF_TOKEN_FILE"; then
  if sudo sh -c "openssl rand -hex 10 > '${BFF_TOKEN_FILE}'" 2>/dev/null; then
    :
  else
    sudo sh -c "head -c 10 /dev/urandom | od -An -tx1 | tr -d ' \n' > '${BFF_TOKEN_FILE}'"
  fi
  ok "首次生成 BFF_ADMIN_TOKEN 并持久化到 ${BFF_TOKEN_FILE}（后续 run 复用）"
fi
BFF_ADMIN_TOKEN="$(sudo cat "$BFF_TOKEN_FILE" 2>/dev/null | tr -d '[:space:]')"
[ -n "$BFF_ADMIN_TOKEN" ] || die "无法生成/读取 ${BFF_TOKEN_FILE}"
cat >"$TMP_CFG" <<EOF
# generated by terraform-hai-platform-single-node $(date -Iseconds)
export KUBECONFIG="${KUBECONFIG_PATH}"
export TASK_NAMESPACE="${TASK_NAMESPACE}"
export PLATFORM_NAMESPACE="${PLATFORM_NAMESPACE}"
export SHARED_FS_ROOT="${SHARED_FS_ROOT}"
export DB_PATH="${HAI_DIR}/db"
export MARS_PREFIX="${MARS_PREFIX}"
export TRAINING_GROUP="${TRAINING_GROUP}"
export JUPYTER_GROUP="${JUPYTER_GROUP}"
export TRAINING_NODES="${TRAINING_NODES}"
export JUPYTER_NODES=" "
export MANAGER_NODES="${MANAGER_NODES}"
export INGRESS_HOST="${INGRESS_HOST}"
export INGRESS_CLASS="${INGRESS_CLASS}"
export HAI_SERVER_ADDR="${HAI_SERVER_ADDR}"
export USER_INFO="${USER_INFO}"
export ROOT_USER="${ROOT_USER}"
export BFF_ADMIN_UID=${BFF_ADMIN_UID}
export BFF_ADMIN_TOKEN="${BFF_ADMIN_TOKEN}"
export BASE_IMAGE="${BASE_IMAGE}"
export TRAIN_IMAGE="${TRAIN_IMAGE}"
export NODE_GPUS=${NODE_GPUS}
export HAS_RDMA_HCA_RESOURCE=${HAS_RDMA_HCA_RESOURCE}
export POSTGRES_USER="${POSTGRES_USER}"
export POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
export REDIS_PASSWORD="${REDIS_PASSWORD}"
EOF
sudo install -o root -g root -m 0640 "$TMP_CFG" "$CONFIG_PATH"
rm -f "$TMP_CFG"
ok "已写入 $CONFIG_PATH"
sudo grep -E "KUBECONFIG|SHARED_FS_ROOT|NODE_GPUS|TRAINING_NODES|MANAGER_NODES|HAI_SERVER_ADDR" "$CONFIG_PATH" | sed 's/^/      /'

step "B. db/redis 数据处理（只动 ${HAI_DIR}）"
case "$HAI_DIR" in
  /nfs-shared/hai-platform) die "拒绝执行：HAI_DIR 指向 VM 平台目录" ;;
esac
DB_HAS_DATA=""
sudo test -d "${HAI_DIR}/db" && [ -n "$(sudo ls -A "${HAI_DIR}/db" 2>/dev/null)" ] && DB_HAS_DATA=1
if [ "${RESET_DATA:-false}" = "true" ]; then
  sudo sh -c "rm -rf '${HAI_DIR}/db'/* '${HAI_DIR}/redis'/*" 2>/dev/null || true
  ok "RESET_DATA=true：已清空 ${HAI_DIR}/{db,redis}（用户/任务数据会全部丢失）"
elif [ -n "$DB_HAS_DATA" ]; then
  warn "检测到 ${HAI_DIR}/db 已有数据 —— 保留（要重装请设 reset_data=true）"
else
  ok "db 目录为空，无需清理"
fi

step "C. hai-up up（首次会拉起 postgres/redis/平台组件，需 2~5 分钟）"
sudo hai-up up -c "$CONFIG_PATH" 2>&1 | sed 's/^/      /'
ok "hai-up up 完成"

step "D. 共享盘权限加固（hai-up 的数据目录是外部 uid 写的）"
sudo chmod -R a+rwX "$HAI_DIR" 2>/dev/null || true
sudo sh -c "test -d '${HAI_DIR}/db' && chmod 700 '${HAI_DIR}/db'" 2>/dev/null || true
ok "权限已加固（db 保持 0700，postgres 要求）"

step "E. 修补 override.toml（pull 策略 + 任务 namespace 合法性）"
# 放在"等 Pod Running"之前：G 步骤会重建平台 Pod，让它一启动就读到修好的 override.toml。
if sudo test -f "$OVERRIDE"; then
  sudo python3 - "$OVERRIDE" "$TASK_NAMESPACE" <<'PYEOF'
import sys

path, ns = sys.argv[1], sys.argv[2]
PULL = "image_pull_policy = 'IfNotPresent'"
CANON = {"internal": "internal = '%s'" % ns, "external": "external = '%s'" % ns}

with open(path, encoding="utf-8") as f:
    lines = f.read().splitlines()
changed = False

# (1) 平台镜像里 core.toml 的 [launcher]/[manager] 没有 pull 策略时默认 Always：
#     每次起任务/manager Pod 都会去 registry 解析 tag，本机没有 registry 凭据时
#     会 ImagePullBackOff，即便镜像已在本地 containerd。
if not any(PULL in ln for ln in lines):
    out, done = [], False
    for ln in lines:
        out.append(ln)
        if not done and ln.strip() == "[launcher]":
            out.append(PULL)
            done = True
    if not done:
        out += ["[launcher]", PULL]
    out += ["", "[manager]", PULL]
    lines = out
    changed = True

# (2) one/hai-up.sh 生成的 [launcher.task_namespaces_by_role] 带模板笔误：
#     external = '<ns>'-external 是**非法 TOML**（单引号字符串后面还跟裸字符），
#     平台组件合并 override.toml 时会直接解析失败。这里按 core.toml 的正确形态改写，
#     顺带把厂商占位 namespace 归一成本实例的 TASK_NAMESPACE。
if not any(ln.strip() == "[launcher.task_namespaces_by_role]" for ln in lines):
    lines += ["", "[launcher.task_namespaces_by_role]", CANON["internal"], CANON["external"]]
    changed = True
else:
    in_section = False
    for i, ln in enumerate(lines):
        s = ln.strip()
        if s.startswith("["):
            in_section = (s == "[launcher.task_namespaces_by_role]")
            continue
        if not in_section:
            continue
        for key, want in CANON.items():
            if s.startswith(key):
                if lines[i] != want:
                    lines[i] = want
                    changed = True
                break

if changed:
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("  patched %s" % path)
else:
    print("  already set")
PYEOF
  ok "override.toml 已处理"
  sudo sed -n '/task_namespaces_by_role/,+3p' "$OVERRIDE" | sed 's/^/      /'
else
  warn "未找到 ${OVERRIDE}，跳过修补"
fi

step "F. 修正平台 Pod 内 kubeconfig 的文件名（KUBECONFIG=/root/.kube/config）"
# one/hai-up.sh 把平台容器/manager 的环境变量硬编码为 KUBECONFIG=/root/.kube/config
# 《one/hai-up.sh:513-514》并把本实例 kubeconfig 原样拷进 kubeconfig 目录 —— 本模块用的是
# /root/.kube/hai-single.conf，拷进去就叫 hai-single.conf，Pod 里 /root/.kube/config 不存在，
# launcher/manager 建任务时会失败。这里补一份 config（不改任何共享文件）。
KC_BASE="$(basename "$KUBECONFIG_PATH")"
KC_SRC="${HAI_DIR}/kubeconfig/${KC_BASE}"
KC_DST="${HAI_DIR}/kubeconfig/config"
if [ "$KC_BASE" = "config" ]; then
  ok "kubeconfig 本身就叫 config（VM 口径），无需处理"
elif sudo test -f "$KC_DST"; then
  ok "已存在 ${KC_DST}"
elif sudo test -f "$KC_SRC"; then
  sudo cp -f "$KC_SRC" "$KC_DST" && sudo chmod 0644 "$KC_DST" \
    && ok "已生成 ${KC_DST}（Pod 内 /root/.kube/config 可用）" \
    || warn "生成 ${KC_DST} 失败"
else
  warn "未找到 ${KC_SRC}，跳过（hai-up 没拷贝 kubeconfig？）"
fi

step "G. 修正平台 StatefulSet（拉取策略 + jupyter 空节点列表 + 浏览器可达的 BFF）"
# 三处都改 StatefulSet 模板，改完重建 Pod：
#   1) one/hai-up.sh:510 把平台 StatefulSet 写死 imagePullPolicy: Always，而本机没有内网
#      registry、镜像只导进了本地 containerd → 平台 Pod 永远 ImagePullBackOff
#      （Failed to pull … not found）。override.toml 里的 image_pull_policy 只管
#      任务/manager Pod，管不到平台自己。
#   2) 本部署刻意没有 jupyter 节点（JUPYTER_NODES=" "，见文件头注释），但镜像里的
#      one/entrypoint.sh 是 `set -e` 且只判断 `JUPYTER_GROUP != ""`，于是会执行
#      `kubectl label nodes   hai_mars_group=jupyter_cpu`（没有节点名）→ 非 0 退出
#      → 容器启动 1 秒即死、CrashLoopBackOff。把容器内的 JUPYTER_GROUP 清空即可跳过该分支；
#      平台运行时用的是 override.toml 的 [jupyter] shared_node_group_prefix，镜像内也没有
#      任何 Python 读这个环境变量（已 grep 核实）。仓库里的 one/entrypoint.sh 已同步修好判空，
#      但已构建的镜像（如 f2cb559）不会因此改变，所以这里按运行期修补。
#   3) one/hai-up.sh:531-532 把 BFF_ADDR 设成 INGRESS_HOST（集群内部服务名），
#      entrypoint 再用它导出 BFF_URL/WS_URL，studio 把它写进页面
#      `window.haiConfig.bffURL` —— 浏览器于是去请求
#      http://hai-platform-svc.hai-platform.svc.cluster.local/proxy/s?endPoint=…
#      这个内部名在部署机上通常被 /etc/hosts 指向 103（宿主 nginx → VM 平台），
#      结果登录代理打到**另一个平台**并返回 403（实测：
#      curl -X POST http://192.168.100.103/proxy/s → 403；把同一个请求发到本实例
#      http://192.168.100.150:8080/proxy/s → success:1）。这里把 BFF_ADDR 指回
#      ${HAI_SERVER_ADDR}:8080，即 studio 自己的、浏览器可达的地址（与 one/hai-up.sh:443
#      的非 k8s 口径一致）：页面与 API 同源，登录/WebSocket 都不再依赖 DNS 改写。
if kube -n "$TASK_NAMESPACE" get sts hai-platform >/dev/null 2>&1; then
  OLD_POD_UID="$(kube -n "$TASK_NAMESPACE" get pod hai-platform-0 -o jsonpath='{.metadata.uid}' 2>/dev/null || true)"
  if kube -n "$TASK_NAMESPACE" patch sts hai-platform \
      -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"hai-platform\",\"imagePullPolicy\":\"IfNotPresent\",\"env\":[{\"name\":\"JUPYTER_GROUP\",\"value\":\"\"},{\"name\":\"BFF_ADDR\",\"value\":\"${HAI_SERVER_ADDR}:8080\"}]}]}}}}" \
      2>&1 | sed 's/^/      /'; then
    ok "hai-platform StatefulSet → IfNotPresent + 空 JUPYTER_GROUP + BFF_ADDR=${HAI_SERVER_ADDR}:8080"
  else
    warn "patch StatefulSet 失败，平台 Pod 可能仍会 ImagePullBackOff / CrashLoopBackOff"
  fi
  kube -n "$TASK_NAMESPACE" delete pod hai-platform-0 --ignore-not-found --wait=false 2>&1 | sed 's/^/      /' || true
  ok "已重建 hai-platform-0"
else
  OLD_POD_UID=""
  warn "未找到 StatefulSet hai-platform（跳过拉取策略修正）"
fi

step "H. 等 hai-platform-0 变成 Running 且 Ready（且确认是新 Pod）"
# 只判 phase=Running 会撞上正在终止的旧 Pod（StatefulSet 是 OrderedReady，新 Pod
# 要等旧 Pod 完全消失才创建），验收就会读到旧的配置——实测踩过：verify 读到的页面
# bffURL 还是修补前的内部服务名。所以这里同时要求 UID 变了、且 Ready=True。
PHASE="$(wait_pod_ready "$TASK_NAMESPACE" hai-platform-0 40 "${OLD_POD_UID:-}" || true)"
[ "$PHASE" = "Running" ] || warn "hai-platform-0 当前 ${PHASE}（继续尝试加固）"
kube -n "$TASK_NAMESPACE" get pods -o wide 2>/dev/null | sed 's/^/      /' || true

step "H2. 校准 DB 里的 bff_admin token（保留 DB 时 token 会漂移）"
# init.sql 只在**首次** init 时写入 bff_admin 行；本模块保留 ${HAI_DIR}/db，
# 所以如果历史 run 用过随机 token（或换过 DB），DB 里的 token 会与容器 env
# BFF_ADMIN_TOKEN 不一致 → studio 的内部调用（list_all / user/info …）403
# → 前端 data_panel 接口 500。这里把 DB 校准成容器正在用的值（无损、无需清库）。
if kube -n "$TASK_NAMESPACE" get pod hai-platform-0 >/dev/null 2>&1; then
  DB_TOKEN="$(kube -n "$TASK_NAMESPACE" exec hai-platform-0 -- \
    psql -U "$POSTGRES_USER" -d mars_db -tAc \
    "select token from \"user\" where user_name='bff_admin'" 2>/dev/null | tr -d '[:space:]' || true)"
  if [ "$DB_TOKEN" = "$BFF_ADMIN_TOKEN" ]; then
    ok "DB bff_admin token 与容器 env 一致"
  elif [ -z "$DB_TOKEN" ]; then
    warn "DB 里没有 bff_admin 行（DB 未初始化？），跳过校准"
  elif kube -n "$TASK_NAMESPACE" exec hai-platform-0 -- \
      psql -U "$POSTGRES_USER" -d mars_db -c \
      "update \"user\" set token='${BFF_ADMIN_TOKEN}' where user_name='bff_admin'" >/dev/null 2>&1; then
    ok "已把 DB bff_admin.token 校准为容器 env 的值（原值 ${DB_TOKEN:0:10}…）"
  else
    warn "校准 DB token 失败，studio 的 data_panel 接口可能仍 500"
  fi
else
  warn "hai-platform-0 不存在，跳过 bff_admin token 校准"
fi

step "I. 确保 Pod 内 redis 真的在跑"
if kube -n "$TASK_NAMESPACE" exec hai-platform-0 -- sh -c "redis-cli -a '${REDIS_PASSWORD}' ping" >/dev/null 2>&1; then
  ok "redis: OK"
else
  warn "redis 未响应，尝试在 Pod 内启动"
  kube -n "$TASK_NAMESPACE" exec hai-platform-0 -- sh -c \
    "service redis-server start; sleep 2; redis-cli -a '${REDIS_PASSWORD}' ping" 2>&1 | tail -3 || \
    warn "启动失败，请查看 Pod 日志"
fi

step "J. 重启 launcher / k8swatcher 让 override 生效"
kube -n "$TASK_NAMESPACE" exec hai-platform-0 -- supervisorctl restart launcher k8swatcher 2>&1 | tail -4 || \
  warn "重启失败，请手工检查"

step "K. 等 LoadBalancer 分配地址（MetalLB 池 ${METALLB_IP_RANGE}）"
LB=""
for i in $(seq 1 30); do
  LB="$(lb_ip)"
  [ -n "$LB" ] && break
  sleep 5
done
if [ -n "$LB" ]; then
  ok "hai-platform-svc EXTERNAL-IP = $LB"
  kube -n "$TASK_NAMESPACE" get svc hai-platform-svc | sed 's/^/      /'
  [ "$LB" = "$HAI_SERVER_ADDR" ] || warn "实际 LB=$LB 与 config 里的 HAI_SERVER_ADDR=$HAI_SERVER_ADDR 不一致，请核对 override.toml"
else
  warn "150s 内未拿到 EXTERNAL-IP，请检查 MetalLB：kubectl -n metallb-system get pods,ipaddresspool"
fi

step "L. 把 fireflyer 的默认 hai-cli 配置指向本平台"
# 目的：登录 103 后直接 `hai-cli whoami / nodes / python ...` 就能用新平台（无需记 HFAI_CLIENT_CONFIG）。
# 安全：原配置先备份；用 point_hai_cli=false 可关闭；其它平台（如 VM 平台）用 HFAI_CLIENT_CONFIG 并行保留。
if [ "${POINT_HAI_CLI:-true}" != "true" ]; then
  warn "POINT_HAI_CLI=false —— 跳过 hai-cli 默认配置切换"
elif [ -z "${LB:-}" ]; then
  warn "没有 LB 地址，跳过 hai-cli 配置"
elif [ "$(id -u)" = "0" ]; then
  warn "当前以 root 运行（terraform 未通过普通用户），跳过；请在 fireflyer 下执行："
  warn "  hai-cli init ${USER_INFO##*:} --url http://${LB}"
else
  TOKEN_HAI="${USER_INFO##*:}"
  mkdir -p "$HOME/.hfai"
  if [ -f "$HOME/.hfai/conf.yml" ] && ! ls "$HOME"/.hfai/conf.yml.vm-platform.bak.* >/dev/null 2>&1; then
    cp -a "$HOME/.hfai/conf.yml" "$HOME/.hfai/conf.yml.vm-platform.bak.$(date +%Y%m%d-%H%M%S)"
    ok "原配置已备份为 ~/.hfai/conf.yml.vm-platform.bak.*"
  fi
  hai-cli init "$TOKEN_HAI" --url "http://$LB" >/dev/null 2>&1 || warn "hai-cli init 返回非 0（继续校验）"
  # hai-cli init 会把 URL 规范成带尾斜杠，下游拼成 "//query/..." 会导致 503，这里去掉尾斜杠。
  sed -i -E "s#^([[:space:]]*url:[[:space:]]*).*#\1http://$LB#" "$HOME/.hfai/conf.yml" 2>/dev/null || true
  if hai-cli whoami >/dev/null 2>&1 && hai-cli nodes >/dev/null 2>&1; then
    ok "hai-cli 默认配置已指向 http://$LB（whoami / nodes 通过）"
    sed -n '1,3p' "$HOME/.hfai/conf.yml" | sed 's/^/      /'
  else
    warn "hai-cli 校验失败，请手工检查 $HOME/.hfai/conf.yml"
  fi
fi
ok "hai-up 阶段完成"
